school/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('school_store.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

school_store/urls.py
from django.urls import path
from . import views


app_name='school_store'
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('new_page/', views.new_page, name='new_page'),
    path('form/', views.form, name='form'),
    path('logout/', views.logout_view, name='logout'),



    path('ajax/load-course/', views.load_course, name='ajax_load_course'),
]

school_store/models.py
from django.db import models
#
# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Course(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Purpose(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Material(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class FormData(models.Model):
    name = models.CharField(max_length=100)
    dob = models.DateField()
    age = models.IntegerField()
    GENDER_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
    ]
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES)
    phone_number = models.CharField(max_length=15)
    email = models.EmailField()
    address = models.TextField()
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    purpose = models.ForeignKey(Purpose, on_delete=models.CASCADE)
    materials = models.ManyToManyField(Material)

    def __str__(self):
        return self.name

school_store/forms.py
from django import forms
from .models import FormData, Department, Course, Purpose, Material


class FormDataForm(forms.ModelForm):
    class Meta:
        model = FormData
        fields = ['name', 'dob', 'age', 'gender', 'phone_number', 'email', 'address', 'department', 'course', 'purpose',
                  'materials']

        widgets = {
            'dob': forms.TextInput(attrs={'type': 'date'}),
            'materials': forms.CheckboxSelectMultiple(),
        }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['course'].queryset = Course.objects.none()

            if 'department' in self.data:
                try:
                    department_id = int(self.data.get('department'))
                    self.fields['course'].queryset = Course.objects.filter(department_id=department_id).order_by('name')
                except (ValueError, TypeError):
                    pass  # invalid input from the client; ignore and fallback to empty City queryset
            elif self.instance.pk:
                self.fields['course'].queryset = self.instance.department.course_set.order_by('name')

class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['name']

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['department', 'name']


class PurposeForm(forms.ModelForm):
    class Meta:
        model = Purpose
        fields = ['name']

class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = ['name']

school_store/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from .forms import FormDataForm,DepartmentForm,CourseForm,PurposeForm,MaterialForm
from .models import Department,Purpose,Course,Material,FormData


def home(request):
    return render(request, "home.html")

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('school_store:new_page')
        else:
            messages.info(request, "Invalid username or password")
            return redirect('school_store:login')
    return render(request, "login.html")

def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        password1 = request.POST['password1']


        if not username or not password or not password1:
            messages.error(request, "Your registration is not completed")
            return redirect('school_store:register')

        if password == password1:
            if User.objects.filter(username=username).exists():
                messages.info(request, "Username already exists")
                return redirect('school_store:register')
            else:
                user = User.objects.create_user(username=username, password=password)
                user.save()
                return redirect('school_store:login')
        else:
            messages.info(request, "Passwords do not match")
            return redirect('school_store:register')
    return render(request, "register.html")

def new_page(request):
    return render(request, "new_page.html")

def form(request):
    form = FormDataForm()
    if request.method == 'POST':
        form=FormDataForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, "order confirmed")
            return redirect('school_store:home')
    return render(request,"form.html",{'form':form})

def logout_view(request):
    logout(request)
    return redirect('school_store:home')


def load_course(request):
    department_id = request.GET.get('department_id')
    courses = Course.objects.filter(department_id=department_id).all()
    return render(request, 'course_dropdown_list_options.html', {'courses': courses})

templates/Home.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

Welcome to our school store..!

{% endblock %}
{% block title %}

SCHOOL STORE
{% endblock %}

{% block content %}
<br>
<div class="container">
    <h1>Welcome to the School Store</h1>
</div>
<div class="container">
    <img class="my_banner" src="{% static 'img/banner.jpg' %}" alt="banner" >
</div>
<div class="container text-right">
  <br>
  <a class="btn btn-primary" href="{% url 'school_store:login' %}">Login</a>
</div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <meta name="description" content="{% block metadescription %}{% endblock %}">

    <title>{% block title %}{% endblock %} </title>
</head>
<body>
{% include 'navbar.html' %}
<div class="container">
    {% block content %}
    {% endblock %}
</div>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/course_dropdown_list_options.html
<option value="">-----</option>
{% for course in courses %}
<option value="{{ course.pk }}">{{ course.name }}</option>
{% endfor %}

templates/form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form method="post" id="personForm" data-course-url="{% url 'school_store:ajax_load_course' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
  </form>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_department").change(function () {
      const url = $("#personForm").attr("data-course-url");
      const departmentId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'department_id': departmentId
        },
        success: function (data) {
          $("#id_course").html(data);
        }
      });

    });
  </script>

</div>
 {%for msg in messages%}
 {{msg}}
 {%endfor%}
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div style="background-color:#F1FAFA;">
<div  class="container">
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="username">Username</label>
        <input type="text" class="form-control" id="username" name="username">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
    <p>Not registered yet? <a href="{% url 'school_store:register' %}">Register here</a></p>
</div>
<div>
{%for msg in messages%}
{{msg}}
{%endfor%}
</div>
{% endblock %}
</div>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'school_store:home' %}"><i class="fa fa-home my_icon"></i></a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'school_store:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'school_store:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'school_store:register' %}">Register</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Department
          </a>
          <ul class="dropdown-menu">
            <li><a href="https://en.wikipedia.org/wiki/Computer_science">Computer Science</a></li>
            <li><a href="https://en.wikipedia.org/wiki/Commerce">Commerce</a></li>
            <li><a href="https://en.wikipedia.org/wiki/Chemistry">Chemistry</a></li>
            <li><a href="https://en.wikipedia.org/wiki/English_language">English</a></li>
            <li><a href="https://en.wikipedia.org/wiki/History">History</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/new_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container" style="background-color:#F1FAFA;">
  <div class="row">
    <h4>Fill up your details <a class="btn btn-success" href="{% url 'school_store:form' %}">here</a></h4>

  </div>
</div>
{% endblock %}

templates/register.html
 {% extends 'base.html' %}
{% load static %}

{% block content %}
 <br>
<div class="container" style="background-color:#F1FAFA;">
 <div class="form-group my_regg_form">
    <form method="post" action="">
        {% csrf_token %}
    <div class="form-group">
        <label >Username
        <input type="text" class="form-control" name="username" placeholder="Enter Your Username"></label>
    </div>
    <div class="form-group">
        <label>Password
        <input type="password" class="form-control"name="password" placeholder="Enter Your Password"></label>
    </div>
    <div class="form-group">
        <label >Confirm Password
        <input type="password" class="form-control" name="password1" placeholder="Confirm Your Password"></label>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>
 </div>
 </div>
 {%for msg in messages%}
 {{msg}}
 {%endfor%}

 {% endblock %}